Messages:
  Reloaded: "&eLotterySix has been reloaded!"
  NoPermission: "&cYou do not have permission to do that!"
  NoConsole: "&cThis command can only be ran by players!"
  InvalidUsage: "&cInvalid Usage!"
  NotEnoughMoney: "&cYou don't have ${Price} in your account!"
  BetPlaced: "&aBet placed! ${Price} deduced from your account!"
  NoGameRunning: "&cNo game is running at the moment"
  GameAlreadyRunning: "&cA game had already been started"
  GameLocked: "&cGame is currently running and locked"
  PreferenceUpdated: "&aSuccessfully updated player preference!"
  GameStarted: "&aStarted new LotterySix game"
  GameSettingsUpdated: "&aUpdated current round of LotterySix"
  BetLimitReachedSelf: "&cYou have reached your bet limit, edit player preferences to change this limit. Please bet responsibly."
  BetLimitReachedPermission: "&cYou have reached your bet limit. Please bet responsibly."
  PlayerNotFound: "&cThat player cannot be found"
  PendingUnclaimed: "&b&lYou have unclaimed balance from LotterySix, click to receive!"
  PendingClaimed: "&aPending balance of ${Money} claimed!"

Explanation:
  Message: "&aFor the explanation on how LotterySix works, please visit: &bhttps://github.com/LOOHP/LotterySix/wiki/LotterySix-Draw-&-Prizes-Explanation"
  URL: "https://github.com/LOOHP/LotterySix/wiki/LotterySix-Draw-&-Prizes-Explanation"
  GUIItem:
    - "&aLotterySix Guide"
    - "&7Information on:"
    - "&7- How the draw works"
    - "&7- How is the probability calculated"
    - "&7- How prizes are allocated"
    - "&7- How the ticket prices are calculated"

Formatting:
  Date: "dd-MM-yyyy HH:mm:ss zzz"

#This option is only used on backend servers
Bungeecord: false

#If you are using LotterySix on Bungeecord mode
#THIS SECTION MUST BE THE SAME ACROSS ALL SERVERS AND PROXY
#Ideally the whole config should be the same across all servers
LotterySix:
  #CornJob expression, https://crontab.guru/
  #How often should the lottery run
  #Put "Never" to never run automatically
  RunInterval: "0 22 * * 2,4,6"
  TimeZone: "Asia/Hong_Kong"
  #How long before the lottery runs after it had started
  #Setting this to a negative value refers to
  #N seconds before the next scheduled round
  #If RunInterval is "Never",
  #A negative value will be treated as positive
  #This is in seconds
  BetsAcceptDuration: -1800
  #This must be a positive EVEN integer
  #If it isn't, it would be rounded up
  PricePerBet: 10
  #Number Of Number Choices, Starting from 1, Inclusive
  #The lower the number of choices, the higher the odds
  #Minimum is 7, Maximum is 49
  NumberOfChoices: 39
  #The lowest prize allocation for winning the top three tiers
  #Ideally you want this value to be MUCH LOWER than
  #the price for betting all numbers divided by 0.45,
  #so you don't win more if you bet every number
  #(MUCH LOWER is still pretty high for high number of choices)
  LowestTopPlacesPrize: 8000000
  #This percentage of total bets acquired will be taken from the prize pool
  TaxPercentage: 0.25

Restrictions:
  #Max amount of money a player can bet in a single round of LotterySix
  #Setting -1 means unlimited
  #To add a player to a group, give the permission "lotterysix.betlimit.<group>"
  #For example "lotterysix.betlimit.vip"
  #Players with no groups will be treated as "default" unless they have "lotterysix.betlimit.unlimited"
  BetLimitPerRound:
    default: -1
    minor: 0

GUI:
  MainMenu:
    Title: "&1LotterySix"
    CheckPastResults:
      - "&dCheck past results"
    NoLotteryGamesScheduled:
      - "&cNo LotterySix games are scheduled"
    CheckOwnBets:
      - "&eNext LotterySix!"
      - "&aDraw Date: {Date}"
      - "&aTurnover: ${TotalBets}"
      - "&aEstimated Prize Pool: ${PrizePool}"
      - "&a"
      - "&bClick to view your placed bets!"
    PlaceNewBets:
      - "&6Place New Bets"
      - "&aPlease bet responsibly"
      - "&a"
      - "&7Odds:"
      - "&7First: 1 in {FIRSTOdds}"
      - "&7Second: 1 in {SECONDOdds}"
      - "&7Third: 1 in {THIRDOdds}"
      - "&7Fourth: 1 in {FOURTHOdds}"
      - "&7Fifth: 1 in {FIFTHOdds}"
      - "&7Sixth: 1 in {SIXTHOdds}"
      - "&7Seventh: 1 in {SEVENTHOdds}"
  LastResults:
    Title: "&2Last Results"
    LotteryInfo:
      - "&aDraw Date: {Date}"
      - "&aTurnover: ${TotalBets}"
      - "&aTotal Prizes: ${TotalPrizes}"
      - "&a"
      - "&a1st Tier Prize: &6${FIRSTPrize} &7x{FIRSTPrizeCount}"
      - "&a2nd Tier Prize: &6${SECONDPrize} &7x{SECONDPrizeCount}"
      - "&a3rd Tier Prize: &6${THIRDPrize} &7x{THIRDPrizeCount}"
      - "&a4th Tier Prize: &6${FOURTHPrize} &7x{FOURTHPrizeCount}"
      - "&a5th Tier Prize: &6${FIFTHPrize} &7x{FIFTHPrizeCount}"
      - "&a6th Tier Prize: &6${SIXTHPrize} &7x{SIXTHPrizeCount}"
      - "&a7th Tier Prize: &6${SEVENTHPrize} &7x{SEVENTHPrizeCount}"
    YourBets:
      - "&aYour Bets"
    NoWinnings: "&7No Winnings"
  YourBets:
    Title: "&2Your Bets"
    Nothing:
      - "&cNo bets placed yet"
  SelectNewBetType:
    Title: "&2Select Bet Type"
    Single:
      - "&6Single Entry"
      - "&7Choose 6 different numbers"
      - "&7Simplest to understand, recommended for first time players"
    Multiple:
      - "&eMultiple Entry"
      - "&7Choose 7 or more different numbers"
      - "&7Example: If seven numbers 1, 2, 3, 4, 5, 6 and 7 are selected,"
      - "&7it can be split into seven single entries as below:"
      - "&7"
      - "&71. 1+2+3+4+5+6"
      - "&72. 1+2+3+4+5+7"
      - "&73. 1+2+3+4+6+7"
      - "&74. 1+2+3+5+6+7"
      - "&75. 1+2+4+5+6+7"
      - "&76. 1+3+4+5+6+7"
      - "&77. 2+3+4+5+6+7"
    Banker:
      - "&aBanker Entry"
      - "&7Choose one to five number(s) as banker(s),"
      - "&7with other numbers selected as legs"
      - "&7Example: If two bankers 1 and 2 with leg numbers 3,4,5,6 and 7 are selected"
      - "&7breakdown of the selections in a 2-banker-and-5-leg-number entry is:"
      - "&7"
      - "&71. 1+2   3+4+5+6"
      - "&72. 1+2   3+4+5+7"
      - "&73. 1+2   3+4+6+7"
      - "&74. 1+2   3+5+6+7"
      - "&75. 1+2   4+5+6+7"
    Random:
      - "&aRandom Entry"
      - "&7No idea what numbers to pick?"
      - "&7Let the computer pick 6 random numbers for you!"
  NewBet:
    SingleTitle: "&2Pick 6 Numbers"
    MultipleTitle: "&2Pick More Than 7 Numbers"
    BankerTitle: "&2Pick Bankers & Numbers"
    Finish:
      - "&eClick to finish selection (${Price})"
    FinishBankers:
      - "&eClick to finish BANKER selection (${Price})"
  ConfirmNewBet:
    Title: "&2Confirm Bet"
    LotteryInfo:
      - "&ePlease bet responsibly"
    Confirm:
      - "&aConfirm Unit Investment (${Price})"
    PartialConfirm:
      - "&aConfirm Partial Unit Investment (${PricePartial})"
    Cancel:
      - "&cCancel"

Announcer:
  PeriodicMessage:
    Message: "&6[LotterySix] Join the next round of LotterySix by placing your bet with [/lottery play]! &eDraw will happen on &a{Date} &ewith an estimated prize pool of &b${PrizePool}&6!"
    #This is in seconds
    Frequency: 900
    #Send this message one more time one minute before scheduled draw
    OneMinuteBefore: true

  DrawCancelledMessage: "&e[LotterySix] LotterySix game on {Date} had been cancelled by an admin or because there are no bets submitted"

  BetPlacedAnnouncement:
    #Whether to announce players placing bets
    #Might be a security risk depending on the type of your server
    Enabled: false
    Message: "&a[LotterySix] &b{Player} &ajust placed a bet worth &b${Price}&a!"

  LiveDrawAnnouncer:
    #Announce drawn numbers as it happens
    Enabled: true
    #Send Title Messages as well
    #If you use this feature, don't set TimeBetween to 0
    SendMessagesTitle: true
    #Time between each number reveal
    #This is in seconds
    TimeBetween: 5
    PreMessage:
      - "&a[LotterySix] Submissions for LotterySix game on {Date} are closed! &eLottery draw will begin shortly, 6 + 1 numbers will be drawn"
    #These will also be sent as title if enabled above
    Messages:
      - "&eLotterySix &aDraw will begin"
      - "&61st Number: {FirstNumber}"
      - "&62nd Number: {SecondNumber}"
      - "&63rd Number: {ThirdNumber}"
      - "&64th Number: {FourthNumber}"
      - "&65th Number: {FifthNumber}"
      - "&66th Number: {SixthNumber}"
      - "&aSpecial Number: {SpecialNumber}"
      - "&b1st Tier Prize: &a${FIRSTPrize} &7x{FIRSTPrizeCount}"
      - "&b2nd Tier Prize: &a${SECONDPrize} &7x{SECONDPrizeCount}"
      - "&b3rd Tier Prize: &a${THIRDPrize} &7x{THIRDPrizeCount}"
    PostMessages:
      - "&e[LotterySix] &aCongratulations winners! Prizes will be given out shortly, here is a recap of the draw results:"
      - "&e[LotterySix] &aDate: {Date}"
      - "&e[LotterySix] &aDraw Results: {FirstNumberOrdered} {SecondNumberOrdered} {ThirdNumberOrdered} {FourthNumberOrdered} {FifthNumberOrdered} {SixthNumberOrdered} &e+ {SpecialNumber}"
      - "&e[LotterySix] &a1st Tier Prize: &6${FIRSTPrize} &7x{FIRSTPrizeCount}"
      - "&e[LotterySix] &a2nd Tier Prize: &6${SECONDPrize} &7x{SECONDPrizeCount}"
      - "&e[LotterySix] &a3rd Tier Prize: &6${THIRDPrize} &7x{THIRDPrizeCount}"
      - "&e[LotterySix] &a4th Tier Prize: &6${FOURTHPrize} &7x{FOURTHPrizeCount}"
      - "&e[LotterySix] &a5th Tier Prize: &6${FIFTHPrize} &7x{FIFTHPrizeCount}"
      - "&e[LotterySix] &a6th Tier Prize: &6${SIXTHPrize} &7x{SIXTHPrizeCount}"
      - "&e[LotterySix] &a7th Tier Prize: &6${SEVENTHPrize} &7x{SEVENTHPrizeCount}"

DiscordSRV:
  DrawResultAnnouncement:
    #Set this to a channel that does not exist to disable
    Channel: "Global"
    Title: "LotterySix Draw Results"
    Description:
      - "**Date: {Date}**"
      - "**Draw Results: {FirstNumberOrdered} {SecondNumberOrdered} {ThirdNumberOrdered} {FourthNumberOrdered} {FifthNumberOrdered} {SixthNumberOrdered} + {SpecialNumber}**"
      - ""
      - "1st Tier Prize: ${FIRSTPrize} x{FIRSTPrizeCount}"
      - "2nd Tier Prize: ${SECONDPrize} x{SECONDPrizeCount}"
      - "3rd Tier Prize: ${THIRDPrize} x{THIRDPrizeCount}"
      - "4th Tier Prize: ${FOURTHPrize} x{FOURTHPrizeCount}"
      - "5th Tier Prize: ${FIFTHPrize} x{FIFTHPrizeCount}"
      - "6th Tier Prize: ${SIXTHPrize} x{SIXTHPrizeCount}"
      - "7th Tier Prize: ${SEVENTHPrize} x{SEVENTHPrizeCount}"
      - ""
      - "*Congratulations!*"
    ThumbnailURL: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8a/Gold_Ingot_JE4_BE2.png"
  SlashCommands:
    Global:
      Messages:
        NotLinked: "Minecraft account must be linked to use this command."
    #SlashCommand /pastdraw
    ViewPastDraw:
      Enabled: true
      Description: "View the draw results of the last LotterySix round"
      NoResults: "No results are available"
      YourBets: "**Your bets**"
      NoWinnings: "No Winnings"
      ThumbnailURL: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8a/Gold_Ingot_JE4_BE2.png"
    #SlashCommand /mybets
    ViewCurrentBets:
      Enabled: true
      Description: "View my bets for the current round of LotterySix"
      Title: "Your Bets"
      SubTitle:
        - "Draw Date: {Date}"
        - "Turnover: ${TotalBets}"
        - "Estimated Prize Pool: ${PrizePool}"
      NoBets: "You haven't placed any bets"
      NoGame: "There are no LotterySix games scheduled"
      ThumbnailURL: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8a/Gold_Ingot_JE4_BE2.png"

Options:
  Updater: true